name: sber_sign_test
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  file_picker: ^5.2.3
  get: ^4.6.5
  dio: ^4.0.6
  curl_logger_dio_interceptor: ^0.0.3
  flutter_svg: ^1.1.6
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg_icons/
    - assets/png_icons/
    - assets/test_files/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SBSansDisplay
      fonts:
        - asset: fonts/SBSansDisplay-Bold.ttf
          weight: 700
        - asset: fonts/SBSansDisplay-Light.ttf
          weight: 300
        - asset: fonts/SBSansDisplay-Regular.ttf
          weight: 400
        - asset: fonts/SBSansDisplay-SemiBold.ttf
          weight: 600
        - asset: fonts/SBSansDisplay-Thin.ttf
          weight: 100
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
